{% set name = "popt" %}
{% set version = "1.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://ftp.osuosl.org/pub/rpm/{{ name }}/releases/{{ name }}-1.x/{{ name }}-{{ version }}.tar.gz
    sha256: c25a4838fc8e4c1c8aacb8bd620edb3084a3d63bf8987fdad3ca2758c63240f9
    patches:
      - 0002-added-sanity-autotest.patch

build:
  number: 0
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - automake  # [unix]
    - autoconf  # [unix]
    - libtool   # [unix]
    - {{ compiler('c') }}
    - perl
    - make
    - gettext
    - patch
  host:
    - libiconv 1.16
  run:
    - libiconv # bounds through run_exports

test:
  commands:
    - test -f $PREFIX/include/popt.h
    - test -f $PREFIX/lib/libpopt.a
    - test -f $PREFIX/lib/libpopt.so  # [linux]
    - test -f $PREFIX/lib/libpopt.dylib  # [osx]

about:
  home: https://rpm5.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Popt is a C library for parsing command line parameters.
  dev_url: https://github.com/rpm-software-management/popt
  doc_url: https://github.com/rpm-software-management/popt/blob/master/README

extra:
  recipe-maintainers:
    - notestaff
    - sodre
