travis:
  secure:
    BINSTAR_TOKEN: XHlNx9/iXd6m1LFkb6vxDdvES43wHfdtJ8BKeLVrhSNJw+cKi5OXExysZzuruB5rh9M5OUNTP4TFWi6fS2OoES1V54bdv6zHUsRQODT4mh/Wo28UoAIieE4Q/mKubDudKY+iXboIHk727yw0dRvbbf3ikPIeptfgVE2kr0y94YHxflzECsihDaRVKX6o4j/duIDoHx7kVIgRbt46DjlMvUveB/4wKdGsOsVOd4wqSuH+vHXBPrstXQO5TZzjqdbBFYlGmRDfMD6WpxslHVkwsK2i4oZiBKXBEdNN1ce3ymvFp5AmOxCzgBudsqFu0BxAduqzsBTO/10b4mV4z81i1dhGvcNrp+ERL5C6jOwZnRM+tclQniFKHquJAuNuDfPo3efrIHgfh7usBFiNx04O1NSwuEP9zRkstKAXVgVF5TzbCip5X+m5A5ns1ePAHWX9fQqPsnHJBIR3uHvKTkrZs+dihWbi4A+6kBU427vvOnVSa7AlAaBMaiNH2JeBToJHva7QDSo/cponIZ/1grS/kQLRwzqDnn2xzei/fTBKhI5grhKCq14MdF1i5R6fpz+/QKQP/zCpHNbO74aIxPxmeySViurXs++6DmB7f4WsvXBBr2z9kAUqHKNJP5CyN2MuPJAjcnzYPhpLpWL3f4hgCOypHMNmcysjT6CH8YB7GG0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
