travis:
  secure:
    BINSTAR_TOKEN: jcs9ncBQxFilcV4dHGMtkBRYy8GDSLMC48cWmCLCPcbOGSTCO+s5r30QJtV34KI47hjQT09QNdzlC1X0wOdRzDYnEBc2u6UFLRMX7ibPd4QITbLv6wk8zWWD10hKkf3gtNs8KiLZo1K3dyyvtZGsIDFEwl6UB6pw3vUSiwM6lm0WdHuIhY2w44iQE+DbkHHlbK7l+0kPS3AAttKegvVwsw4+LwEt0Yc6wWxIs2a1mgklR6vyf7NREfXvdY01ZcYCFv3e2zsK3PCRrcVVvAvmrQyh5/lD2tKE+mo2ZVqXjmesShUNy61wwdot8j+rI/ibTnCVZtW/z7v7qvaKCWoOA4v92++X9JOVDHsJuXt/vrrXmbzN85SsUwLxC5PyruRywjfyS7LqurSLz19W3mpaNPumV9OYbUirZklCFN2nStbvIttg7zQkENWjIykvRobAvc7qSfkoMgVwz0IAHWTiX31FnkkxKVEhHnVlYUgi+U/2EngERCUioebWm6IHFDqDskiOld6YZMeki+Rk7T6m+ZLy8M2USvqmU0IGWCJUWc8mnUzX5DH12+MVuFn9QUTqMK9z4Z1c9fHbfKqSCqM8NsqyfZZLk5Um72HR2oAjotnYZNEfnCT24QkrsvcwepC3dQGZG/mbluybbwedGAD9ujz9Wa02X1jegeWJDVJAq+0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
